### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ollym** [vlado/open_exchange_rates#3]
```
[GEM_ROOT]/gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/response.rb:11 :in `rates`
[GEM_ROOT]/gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/rates.rb:37 :in `exchange_rate`
[GEM_ROOT]/gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/rates.rb:59 :in `convert`
```

**Comment by vlado** [comment]
Hi @ollym, thanks for reporting. It would be great if you could send some more info for debugging (steps you took, ...).

**Comment by ollym** [comment]
@vlado it's really intermittent. I think it might be rate limiting by the OpenExchangeRate API or a server error or something? I can't recreate it, just every now and again it comes up in my logs.

**Comment by cabello** [comment]
Maybe get the input params, currency, date range?

**Comment by vlado** [comment]
I'm closing this for now. It would be best to make sure that you handle failures like this (rate limit, network error, server error, ...) in your app.
