### ISSUE TITLE
Wanna know why App ID is needed.

### ISSUE THREAD

**Issue by karlentwistle** [vlado/open_exchange_rates#4]
The README has a broken URL in 

Configuration

You will need App ID to use OpenExchangeRates, you can get one here for free. Wanna know why App ID is needed.

http://www.josscrowcroft.com/2012/projects/open-exchange-rates-update-the-partys-not-over-it-just-got-a-little-too-noisy/

**Comment by vlado** [comment]
Hi @karlentwistle, this is now fixed :)

Thanks for reporting :+1:
