### ISSUE TITLE
redirection forbidden

### ISSUE THREAD

**Issue by SchlauFuchs** [vlado/open_exchange_rates#8]
lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://openexchangerates.org/latest.json?app_id=[redacted] -> https://openexchangerates.org/latest.json?app_id=[redacted] (RuntimeError)
    from /home/deploy/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/open-uri.rb:146:in`open_uri'
    from /home/deploy/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /home/deploy/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/open-uri.rb:33:in`open'
    from gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/rates.rb:94:in `parse_latest'
    from gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/rates.rb:63:in`latest'
    from gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/rates.rb:36:in `exchange_rate'
    from lib/exchange_rate_updater.rb:27:in`retrive_rate'

**Comment by vlado** [comment]
@SchlauFuchs thanks for reporting. It is fixed with https://github.com/vlado/open_exchange_rates/pull/9 and I've released new version of the gem with fix included (0.5.0)
